spring:
  application:
    name: Task-Manager
  data:
    mongodb:
      uri: mongodb://admin:password@mongo:27017/testdb?authSource=admin


springdoc:
  override-with-generic-response: false
  remove-default-responses: true

